name: Send Expiry Summary

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6:00 AM UTC. Adjust as needed.
  workflow_dispatch: # Allows manual triggering

jobs:
  send-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: scripts
        run: npm install

      - name: Run summary script
        working-directory: scripts
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        run: node send-summary.js
